# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: redis-server version 7.x install
      run: |
        sudo add-apt-repository ppa:redislabs/redis
        sudo apt update
        sudo apt install -y redis-tools redis-server
        redis-server --version
        redis-server ./tests/redis-test.conf

    - name: set redis pw env vars
      run: echo "PETNET_DBAUTH=testpw" >> $GITHUB_ENV

    - name: verify redis running
      run: |
        echo "the value of PETNET_DBAUTH is $PETNET_DBAUTH"
        redis-cli -a "$PETNET_DBAUTH" ping

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install

    - name: Lint with ruff and pylint
      run: |
        poetry run ruff check ./petnet_app/
        poetry run pylint ./petnet_app/
    - name: Unit Tests
      run: |
        poetry run pytest -m "not redis" --cov=petnet_app/ --cov-branch tests/
    - name: mypy
      run: |
        poetry run mypy petnet_app/
